---
- hosts: localhost
  tasks:
    - name: example ec2 group
      ec2_group:
        name: dbsg
        description: an example EC2 group
        vpc_id: vpc-0dd3b6057a0a1c710
        region: us-east-1
        rules:
          - proto: tcp
            from_port: 3306
            to_port: 3306
            cidr_ip: 0.0.0.0/0
      register: dbsg
    - debug:
        var: dbsg
    - rds_subnet_group:
        state: present
        region: us-east-1
        name: dbsubnet_pk
        description: My Fancy Ex Parrot Subnet Group
        subnets:
          - subnet-0355d46b1fdb1e454
          - subnet-076e27a5d4cd44d53
      register: dbsubnet_pk
    - debug:
        var: dbsubnet_pk
    - rds:
        command: create
        region: us-east-1
        instance_name: myapp-database_pk
        db_name: userdb
        db_engine: MySQL
        size: 10
        instance_type: db.t2.micro
        username: mysql_admin
        password: 1nsecure
        subnet: dbsubnet_pk
        license_model: "general-public-license"
        vpc_security_groups: "{{ dbsg.group_id }}"
        multi_zone: no
        wait: yes
        wait_timeout: 900
      register: mydb
    - debug:
        var: mydb
    - replace:
        path: ../feandbe/threetier.yaml
        regexp: 'DATABASENAME'
        replace: "{{ mydb.instance.endpoint }}"
        backup: yes
